#!/bin/sh
# postinst script for cogfly
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

package_type=deb


case "$1" in
    configure)
xdg-desktop-menu install /opt/cogfly/lib/cogfly-Cogfly.desktop
ln -sf /opt/cogfly/bin/Cogfly /usr/local/bin/cogfly
curl -fsSL https://apt.ambershadow.dev/repo.gpg -o /usr/share/keyrings/cogfly.gpg
curl -fsSL https://apt.ambershadow.dev/cogfly.sources -o /etc/apt/sources.list.d/cogfly.sources
apt-get update || true
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0