name: jpackage
on:
  push:
    branches:
      - master

jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: liberica
          java-version: 25
          architecture: x64

      - name: Make Gradle wrapper executable
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Build project
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            ./gradlew.bat clean shadowJar
          else
            ./gradlew clean shadowJar
          fi

      - name: Get version
        shell: bash
        run: |
          echo "ver=$(./gradlew -q ver)" >> "$GITHUB_ENV"
          echo ${{ env.ver }}

      - name: Build macOS dmg
        if: runner.os == 'macOS'
        run: |
          jpackage \
              --input build/libs \
              --main-jar Cogfly-${{ env.ver }}.jar \
              --main-class dev.ambershadow.cogfly.Cogfly \
              --name "Cogfly" \
              --type dmg \
              --vendor "Ambershadow" \
              --icon ./icons/icon.icns \
              --app-version ${{ env.ver }} \
              --dest output/${{ runner.os }} \
              --resource-dir plist \
              --verbose

      - name: Build Windows EXE
        if: runner.os == 'Windows'
        run: |
          jpackage `
            --input build/libs `
            --main-jar Cogfly-${{ env.ver }}.jar `
            --main-class dev.ambershadow.cogfly.Cogfly `
            --name Cogfly `
            --type app-image `
            --vendor "Ambershadow" `
            --icon ./icons/icon.ico `
            --app-version ${{ env.ver }} `
            --dest output/${{ runner.os }} `
            --verbose
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "/DCogflyVersion=""${{ env.ver }}""" Cogfly.iss
      - name: Build DEB
        if: runner.os == 'Linux'
        run: |
          jpackage \
            --input build/libs \
            --main-jar Cogfly-${{ env.ver }}.jar \
            --main-class dev.ambershadow.cogfly.Cogfly \
            --name Cogfly \
            --type deb \
            --vendor "Ambershadow" \
            --icon ./icons/icon.png \
            --app-version ${{ env.ver }} \
            --dest output/${{ runner.os }} \
            --resource-dir desktop \
            --verbose

      - name: Build RPM
        if: runner.os == 'Linux'
        run: |
          jpackage \
            --input build/libs \
            --main-jar Cogfly-${{ env.ver }}.jar \
            --main-class dev.ambershadow.cogfly.Cogfly \
            --name Cogfly \
            --type rpm \
            --vendor "Ambershadow" \
            --icon ./icons/icon.png \
            --app-version ${{ env.ver }} \
            --dest output/${{ runner.os }} \
            --resource-dir desktop \
            --verbose

      - name: Build APPIMAGE
        if: runner.os == 'Linux'
        run: |
          mkdir -p output/appimage
          mkdir -p output/${{ runner.os }}
          jpackage \
            --input build/libs \
            --main-jar Cogfly-${{ env.ver }}.jar \
            --main-class dev.ambershadow.cogfly.Cogfly \
            --name Cogfly \
            --type app-image \
            --vendor "Ambershadow" \
            --icon ./icons/icon.png \
            --app-version ${{ env.ver }} \
            --dest output/appimage \
            --verbose 
          cp ./icons/icon.png output/appimage/Cogfly/
          cp ./desktop/Cogfly_appimage.desktop output/appimage/Cogfly/Cogfly.desktop
          cat > output/appimage/Cogfly/AppRun << 'EOF'
          #!/bin/sh
          export _JAVA_AWT_WM_NONREPARENTING=1
          HERE="$(dirname "$(readlink -f "$0")")"
          exec "$HERE/bin/Cogfly" "$@"
          EOF
          chmod +x output/appimage/Cogfly/AppRun
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
          chmod +x appimagetool
          ls -l output/appimage/Cogfly
          export APPIMAGE_EXTRACT_AND_RUN=1
          ./appimagetool \
            -u "gh-releases-zsync|${{ github.repository_owner }}|Cogfly|latest|Cogfly-*.AppImage" \
            output/appimage/Cogfly output/${{ runner.os }}/Cogfly-${{ env.ver }}.AppImage

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Cogfly-${{ runner.os }}
          path: output/${{ runner.os }}
          retention-days: 14
